name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
           cd "CARS Launcher"
           chmod +x gradlew
           ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: "CARS Launcher/app/build/outputs/apk/debug/app-debug.apk"
